title: Phuc's Portfolio
markdown: kramdown

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title/

exclude:
  - manage.py
  - build.rb
  - goodreads_library_export.csv
  - README.md
  - LICENSE
  - vendor/
  - __pycache__/
